version: "3.8"
services:
    api:
     build:
       context: ./
       dockerfile: Dockerfile
     command: ["--host", "0.0.0.0", "api:app", "--reload"]
     environment:
       - LOG_LEVEL=debug
       - FINHUB_REPOSITORY_URL=https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/day/2020-01-01/2020-12-31?adjusted=true&sort=asc&limit=120&apiKey=8YWgCP8lOZl3z4jFVy8sQSu2HQJnCLPn
     ports:
       - "8000:8000"
     restart: on-failure
     volumes:
       - ./api:/app/api

